application: seivadnosaj
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static/about.html
  upload: static/about.html

- url: /jquery.min.js
  static_files: static/jquery.min.js
  upload: static/jquery.min.js

- url: .*
  script: main.py
